### ISSUE TITLE
Updated Needed

### ISSUE THREAD

**Issue by Radvendii** [jakubfijalkowski/hlibsass#9]
Something similar to #3 seems to be happening again, where the latest version of libsass isn't supported.

Can someone else confirm though? I'm not super confident this is what's going wrong. I'm coming from NixOS/nixpkgs#38253.

**Comment by jakubfijalkowski** [comment]
As far as I can understand the issue, the problem is with the LibSass/hLibsass version combination. LibSass has had breaking changes between versions 3.4.x and 3.5.x (and earlier lines as well) and hLibsass had to have breaking changes as well. Moreover, I can only guarantee that exact version of hLibsass works with corresponding version of LibSass and nothing more (it is stated in [README](https://github.com/jakubfijalkowski/hlibsass#hlibsass-and-libsass-version)).

It seems like the user is trying to build hLibSass 0.1.6.1 against LibSass 3.5.4 and that is not supported. 3.5.4 may work only with version 0.1.7.0 (it was tested agains 3.5.2 but from the git diff it seems like there were no changes that would make hLibsass incompatible).

Unfortunately, I don't know Nix nor NixOs (still trying to find the time to learn it ;) ) and might be unable to help, but I can give you assistance in solving the problem (if it does not require access to PC - I broke mine last week and still haven't found a replacement).

**Comment by Radvendii** [comment]
Ah, I understand. So we have the wrong version numbers happening in Nixpkgs, and it's not an issue with hlibsass at all. Thank you so much for the help.
